---
- name: Create global configuration directory
  file:
    path: /etc/pg_back
    state: directory
    owner: postgres
    group: postgres
- name: Copy over pg_back global config
  template:
    src: pg_back.conf.j2
    dest: /etc/pg_back/pg_back.conf
    owner: postgres
    group: postgres
- name: Download the pg_back script and install it
  get_url:
    url: "{{ pgback_download_url }}"
    dest: "{{ pgback_install_directory }}/pg_back"
    mode: 'u=rwx,g=rx,o=rx'
