---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: postgres:10-alpine
    override_command: false
    env:
      POSTGRES_HOST_AUTH_METHOD: trust
provisioner:
  name: ansible
verifier:
  name: ansible
